name: Publish NPM package
on:
  push:
    tags:
        - v*

jobs:
  publish-npm-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: webfactory/ssh-agent@v0.5.4
        with:
          # https://github.com/marketplace/actions/webfactory-ssh-agent#using-multiple-keys
          ssh-private-key: ${{ secrets.PERP_LUSHAN_DEPLOY_PRIVATE_KEY }}

      # See: https://github.com/actions/cache/blob/main/examples.md#node---yarn
      - name: Get Yarn cache directory
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Use Yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
            path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
            key: ${{ runner.os }}-yarn-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install package dependencies
        run: yarn install --prefer-offline --frozen-lockfile --network-concurrency 1

      - name: Publish npm package
        run: yarn release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Extract version from package.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: 'jq .version output/package.json -r'

      - name: Discord notification
        env:
            DISCORD_WEBHOOK: ${{ secrets.DISCORD_RELEASE_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
            args: "npm package @perp/curie-periphery-contract ${{ steps.version.outputs.value }} released"
