name: Testing

on: [push]

jobs:
  contract-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      # https://github.com/marketplace/actions/webfactory-ssh-agent#using-multiple-keys
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.PERP_LUSHAN_DEPLOY_PRIVATE_KEY }}

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile --network-concurrency 1

      - name: Build packages
        run: yarn build

      - name: Run tests
        run: yarn test-parallel
        env:
          # to solve problem of memory leak https://stackoverflow.com/a/59572966
          NODE_OPTIONS: "--max-old-space-size=4096"

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      # https://github.com/marketplace/actions/webfactory-ssh-agent#using-multiple-keys
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.PERP_LUSHAN_DEPLOY_PRIVATE_KEY }}

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile --network-concurrency 1

      - name: Run lint
        run: yarn lint
